version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/chink

hooks:
  BeforeInstall:
    - location: deploy/install-deps.sh
      timeout: 600
      runas: ec2-user
#  AfterInstall:
#    - location: deploy/set-permissions.sh
#      timeout: 600
#      runas: ec2-user
  ApplicationStart:
    - location: deploy/npm-start.sh
      timeout: 120
      runas: ec2-user
