version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/chink

hooks:
  BeforeInstall:
    - location: deploy/application-stop.sh
      timeout: 600
      runas: ec2-user
  AfterInstall:
    - location: deploy/after-install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: deploy/application-start.sh
      timeout: 120
      runas: ec2-user
