import { readFileSync, writeFileSync } from 'fs'
import { formatSsmParameters } from '../src/utils/formatSsmParameters'
import SSM = require('aws-sdk/clients/ssm')

const initDockerCompose = () => {

    const ssm: SSM = new SSM({
        apiVersion: '2014-11-06',
        region: 'us-east-1'
    })

    const params = {
        Names: [
            'HostPort',

            'GithubClientId',
            'GithubClientSecret',

            'PgHost',
            'PgPort',
            'PgDatabase',
            'PgUser',
            'PgPassword',
        ],
        WithDecryption: false
    }

    ssm.getParameters(params, (err, data) => {
        if (err) {
            console.log(err, err.stack)
        } else {
            const storeParameters: { [key: string]: string } = <any> formatSsmParameters(data)

            const values: { [key: string]: string } = {
                'POSTGRES_DB': 'PgDatabase',
                'POSTGRES_USER': 'PgUser',
                'POSTGRES_PASSWORD': 'PgPassword',
                'POSTGRES_EXTERNAL_PORT': 'PgPort',
                'POSTGRES_INTERNAL_PORT': 'PgPort',
            }

            let content = readFileSync('./deploy/docker-compose.template.yml', 'utf8')

            Object.keys(values).forEach((key: string) => {
                content = content.replace(`%${key}%`, storeParameters[values[key]])
            })

            content = `## This file is autogenerated on ${new Date()} ##\n\n${content}`

            writeFileSync('./docker-compose.prod.yml', content)

        }
    })

}

initDockerCompose()