-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id SERIAL,

    primary_git_service_name character varying(10),
    primary_git_service_user_id character varying(150),
    primary_git_service_profile json,

    secondary_git_service_name character varying(10),
    secondary_git_service_user_id character varying(150),
    secondary_git_service_profile json,

    CONSTRAINT unique_service_name_and_user_id_pair UNIQUE (primary_git_service_name, primary_git_service_user_id),

    CONSTRAINT check_git_service_name
       CHECK (primary_git_service_name = 'gitlab' OR primary_git_service_name = 'github')
);
